#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["package-airflow-blue", "blue"]
#
# [tool.uv.sources]
# package-airflow-blue = { git = "https://github.com/getcolors/airflow.git", rev = "bb16cbe8341672f7a91bbb0d4de3663b982cda51", subdirectory = "blue" }
# blue = { git = "https://github.com/getcolors/blue.git", rev = "369c5aafea790a03b649b3513003651e672f3f57" }
# ///
"""Thin launcher for package-airflow-blue."""
from package_airflow_blue import exec, run

__all__ = ["run"]

if __name__ == "__main__":
    exec()
