#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["package-airflow-blue"]
#
# [tool.uv.sources]
# package-airflow-blue = { git = "https://github.com/getcolors/airflow.git", rev = "39865b758ee695a994bf6eab6a41fcf7f1ab7929", subdirectory = "blue" }
# ///
"""Thin launcher for package-airflow-blue."""
from package_airflow_blue import exec, run

__all__ = ["run"]

if __name__ == "__main__":
    exec()
