import {existsSync,mkdirSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from "node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import{runPlan}from"red/process";import{runtime,type ExecResult}from"red/runtime";import type{Opts}from"red/workflow";
export type Runner=(cmd:string[],opts?:{env?:Record<string,string|undefined>;timeoutMs?:number})=>Promise<ExecResult>;const run:Runner=(c,o={})=>runtime.exec(c,{...o,timeoutMs:o.timeoutMs??30000});const placeholder="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBUILDPLACEHOLDER0000000000000000000000";export const deployUser="deploy";
export const dagsRepo=(o:Opts)=>String(o["dags-repo"]??"").trim()||undefined;export const keyComment=(o:Opts)=>`airflow-deploy-${o.profile||"default"}-${dagsRepo(o)?.replaceAll("/","-")}`;
export function placeholderKeys(o:Opts){const g=dagsRepo(o);return g?[{github:g,public:`${placeholder} ${keyComment(o)}`}]:[]} export const publicKeys=(o:Opts)=>((o["airflow/deploy-keys"] as any[])||[]).map(({public:pub})=>({public:pub}));
export async function generateKeys(o:Opts,r:Runner=run):Promise<[any[],string?]>{const g=dagsRepo(o);if(!g)return[[]];const d=mkdtempSync(join(tmpdir(),"airflow-deploy")),p=join(d,"key-0"),x=await r(["ssh-keygen","-t","ed25519","-N","","-q","-C",keyComment(o),"-f",p]);return x.exit?[[],`ssh-keygen failed for ${g}: ${String(x.err).trim()}`]:[[{github:g,public:readFileSync(`${p}.pub`,"utf8").trim(),privateFile:p}]]}
export const hostKeyArgs=(o:Opts)=>["ssh","-o","BatchMode=yes","-o","ConnectTimeout=10","-o","StrictHostKeyChecking=accept-new",`${o.user||"root"}@${o.ip}`,"cat /etc/ssh/ssh_host_ed25519_key.pub"];
export function knownHostsLine(ip:unknown,pub:unknown){const[a,b]=String(pub??"").trim().split(/\s+/);return a?.startsWith("ssh-")&&b?`${ip} ${a} ${b}`:undefined} export async function fetchHostKey(o:Opts,r:Runner){const x=await r(hostKeyArgs(o));return x.exit===0?knownHostsLine(o.ip,x.out):undefined}
const envName=(o:Opts)=>String(o.profile||"default"),q=(x:unknown)=>`'${String(x).replaceAll("'","'\\''")}'`;
export function createRepoCommands(o:Opts){return[{label:`create ${dagsRepo(o)}`,args:["gh","repo","create",dagsRepo(o)!,"--private","--add-readme","--description",`Airflow DAGs for ${o["airflow-host"]}, deployed by colors`]}]}
export function publishCommands(o:Opts,k:any){const g=k.github,e=envName(o),b=["--repo",g,"--env",e];return[{label:`${g} environment ${e}`,args:["gh","api","--method","PUT","--silent",`repos/${g}/environments/${e}`]},{label:`${g} SERVER_IP`,args:["gh","variable","set","SERVER_IP",...b,"--body",String(o.ip)]},{label:`${g} SERVER_USER`,args:["gh","variable","set","SERVER_USER",...b,"--body",deployUser]},{label:`${g} SSH_KNOWN_HOSTS`,args:["gh","variable","set","SSH_KNOWN_HOSTS",...b,"--body",String(o["airflow/known-hosts"]??"")]},{label:`${g} SSH_PRIVATE_KEY`,args:["sh","-c",`gh secret set SSH_PRIVATE_KEY --repo ${q(g)} --env ${q(e)} < ${q(k.privateFile)}`]}]}
export function revokeCommands(o:Opts){const g=dagsRepo(o)!,e=envName(o),b=["--repo",g,"--env",e];return["SERVER_IP","SERVER_USER","SSH_KNOWN_HOSTS"].map(n=>({label:`${g} ${n}`,args:["gh","variable","delete",n,...b]})).concat([{label:`${g} SSH_PRIVATE_KEY`,args:["gh","secret","delete","SSH_PRIVATE_KEY",...b]}])}
export async function repoExists(o:Opts,r:Runner){return(await r(["gh","repo","view",dagsRepo(o)!,"--json","name"],{env:{GH_TOKEN:String(o["github-token"])}})).exit===0}
export const sshRemote=(o:Opts)=>`git@github.com:${dagsRepo(o)}.git`;
export async function seedRepo(o:Opts,files:any[],r:Runner):Promise<string|undefined>{if(!files.length)return;const d=mkdtempSync(join(tmpdir(),"airflow-seed"));try{let x=await r(["git","clone","--depth","1",sshRemote(o),d],{timeoutMs:120000});if(x.exit)return`could not clone ${sshRemote(o)} over SSH: ${String(x.err).trim()}\nThe seed is pushed with your own SSH key rather than the GitHub token, so this needs an SSH key GitHub accepts.\nCheck \`ssh -T git@github.com\`.`;const missing=files.filter(f=>!existsSync(join(d,f.path)));if(!missing.length)return;for(const f of missing){const p=join(d,f.path);mkdirSync(join(p,".."),{recursive:true});writeFileSync(p,f.content)}x=await r(["git","-C",d,"add","--",...missing.map(f=>f.path)],{timeoutMs:120000});if(x.exit)return`git add failed: ${String(x.err).trim()}`;x=await r(["git","-C",d,"-c","user.name=colors airflow","-c","user.email=airflow@getcolors.ai","commit","-m","Seed the deploy workflow and an example DAG"],{timeoutMs:120000});if(x.exit)return`git commit failed: ${String(x.err).trim()}`;x=await r(["git","-C",d,"push","origin",`HEAD:${o["dags-branch"]||"main"}`],{timeoutMs:120000});if(x.exit)return`could not push the seed to ${o["dags-branch"]||"main"}: ${String(x.err).trim()}`;}finally{rmSync(d,{recursive:true,force:true})}}
function cleanup(o:Opts){if(typeof o["airflow/key-dir"]==="string")rmSync(o["airflow/key-dir"] as string,{recursive:true,force:true});const{"airflow/key-dir":_,...rest}=o;return{...rest,"airflow/deploy-keys":((o["airflow/deploy-keys"]as any[])||[]).map(({privateFile,...k})=>k)}}
export async function githubStep(o:Opts,r:Runner=run):Promise<Opts>{const ev=o["red/event"],del=ev==="delete";if(!["create","delete"].includes(String(ev))||!dagsRepo(o))return o;if(!del)o={...o,"airflow/known-hosts":await fetchHostKey(o,r)};const cmds=del?revokeCommands(o):[...(!(await repoExists(o,r))?createRepoCommands(o):[]),...((o["airflow/deploy-keys"]as any[])||[]).flatMap(k=>publishCommands(o,k))],env={GH_TOKEN:String(o["github-token"])};const result=await runPlan(cmds,{runner:c=>r(c.args,{env}),continueOnError:()=>del});let fail=result.exit?`gh failed for ${result.command?.label}: ${String(result.err).trim()}`:undefined;if(!del&&!fail)fail=await seedRepo(o,(o["airflow/seed-files"]as any[])||[],r);const z=cleanup(o);return fail?{...z,"red/exit":1,"red/err":fail}:{...z,"red/exit":0}}
