import { readFileSync } from "node:fs"; import { dirname, isAbsolute, join } from "node:path";
import { ansibleStep, ansibleWithSpec } from "red/ansible"; import { parName } from "red/cli"; import { scaffold,type Spec,type Template } from "red/scaffold"; import * as tofu from "red/tofu"; import type {Opts} from "red/workflow";
import { tools as onceTools } from "package-once-red"; import * as github from "./github.ts"; import {hostAlias,withOnceShape} from "./utils.ts"; import {tofuEnv} from "./validate.ts";
import raw from "../resources/raw" with {type:"text"}; import localCfg from "../resources/tools/ansible-local/ansible.cfg" with {type:"text"}; import localInv from "../resources/tools/ansible-local/inventory.ini" with {type:"text"}; import localMain from "../resources/tools/ansible-local/main.yml" with {type:"text"}; import remoteCfg from "../resources/tools/ansible-remote/ansible.cfg" with {type:"text"}; import remoteMain from "../resources/tools/ansible-remote/main.yml" with {type:"text"};
import authorizedKeys from "../resources/tools/ansible-remote/files/authorized-keys" with {type:"text"}; import compose from "../resources/tools/ansible-remote/files/docker-compose.yml" with {type:"text"}; import caddy from "../resources/tools/ansible-remote/files/Caddyfile" with {type:"text"}; import walgWrapper from "../resources/tools/ansible-remote/files/wal-g-wrapper" with {type:"text"}; import walgBase from "../resources/tools/ansible-remote/files/walg-basebackup" with {type:"text"}; import walgCheck from "../resources/tools/ansible-remote/files/walg-check" with {type:"text"}; import walgNotify from "../resources/tools/ansible-remote/files/walg-notify" with {type:"text"}; import firewall from "../resources/tools/tofu/digitalocean/firewall.tf" with {type:"text"}; import deployDags from "../resources/tools/github/deploy-dags.yml" with {type:"text"}; import helloWorld from "../resources/tools/github/hello_world.py" with {type:"text"};
export const computeTool="airflow-compute",ansibleLocalTool="airflow-ansible-local",ansibleRemoteTool="airflow-ansible-remote",githubTool="airflow-github",dnsTool="tofu-dns",smtpTool="tofu-smtp",smtpPostTool="tofu-smtp-post";
const opts={tagOpen:"<",tagClose:">",filterOpen:"{",filterClose:"}"}; const tmpl=(name:string,content:string):Template=>({name,content}); const spec=(t:Template,target:string,data:Opts):Spec=>({template:t,target,data,opts}); const rawSpec=(target:string,content:string)=>spec(tmpl("airflow/raw",raw),target,{content});
export function toolDir(o:Opts,tool:string){const w=String(o.workdir||".colors"),sf=o["red/state-file"];const root=!isAbsolute(w)&&typeof sf==="string"?join(dirname(sf),w):w;return `${root}/${o.profile||"airflow"}/${tool}`}
export const delegatedToolDir=(o:Opts,t:string)=>onceTools.toolDir(o,t);
function credentialEnv(o:Opts,...slots:string[]){const m=Object.assign({},...[...slots,"provider-backend"].map(s=>tofuEnv(o,s)));const e=Object.fromEntries(Object.entries(m).flatMap(([k,v])=>o[k]==null||String(o[k])===""?[]:[[v,String(o[k])]]));return Object.keys(e).length?e:undefined} export const backendCredentialEnv=(o:Opts)=>credentialEnv(o);
export function fallbackComputeParams(o:Opts){const n=String(o.profile||"airflow");if(["azure","aws","google"].includes(String(o["provider-compute"])))return{ip:"192.168.0.1",sudoer:"ubuntu",uid:"1000",name:n,user:"ubuntu"};if(o["provider-compute"]==="oci")return{ip:"192.168.0.1",sudoer:"ubuntu",uid:"1001",name:n,user:"ubuntu"};if(o["provider-compute"]==="yandex")return{ip:"192.168.0.1",sudoer:"ubuntu",uid:"1000",name:n,user:"ubuntu"};if(o["provider-compute"]==="no-infra")return{ip:o["no-infra-compute-ip"]||"192.168.0.1",sudoer:o["no-infra-compute-sudoer"]||"root",...(o["no-infra-compute-uid"]!=null?{uid:o["no-infra-compute-uid"]}:{}),name:n,user:o["no-infra-compute-user"]||"root"};return{ip:"192.168.0.1",sudoer:"root",name:n,user:"root"}}
export function cidrList(o:Opts,k:string){const v=o[k],xs=(Array.isArray(v)?v:String(v??"").split(/[,\s]+/)).map(String).map(x=>x.trim()).filter(Boolean);return xs.length?xs:["0.0.0.0/0","::/0"]} export const firewallEnabled=(o:Opts)=>o["provider-compute"]==="digitalocean"&&o["digitalocean-firewall"]!==false;
function onceResource(provider:string){const entry=Bun.resolveSync("package-once-red",import.meta.dir);return readFileSync(join(dirname(entry),`../resources/tools/tofu/${provider}/main.tf`),"utf8")}
export function computeSpecs(o:Opts,dir:string):Spec[]{const p=String(o["provider-compute"]||"digitalocean"),data={...o,"ssh-sources-hcl":tofu.hclList(cidrList(o,"digitalocean-ssh-sources")),"http-sources-hcl":tofu.hclList(cidrList(o,"digitalocean-http-sources"))};const r=[spec(tmpl(`once/tools/tofu/${p}/main.tf`,onceResource(p)),`${dir}/main.tf`,data)];if(firewallEnabled(o))r.push(spec(tmpl("airflow/tools/tofu/digitalocean/firewall.tf",firewall),`${dir}/firewall.tf`,data));return r}
export async function computeStep(o:Opts){const dir=toolDir(o,computeTool),fallback=fallbackComputeParams(o),r=await tofu.tofuWithSpec(o,computeSpecs(o,dir),{dir,env:credentialEnv(o,"provider-compute")});if((r["red/exit"]??0)>0||o["red/event"]==="delete")return r;if(o["red/event"]==="build")return{...r,...fallback,"once/compute-params":fallback};const p={...fallback,...((r["tofu/outputs"] as any)?.params||{})};return{...r,...p,"once/compute-params":p}}
export const smtpStep=(o:Opts)=>onceTools.tofuSmtpStep(withOnceShape(o)); export const dnsStep=(o:Opts)=>onceTools.tofuDnsStep(withOnceShape(o)); export const smtpPostStep=(o:Opts)=>onceTools.tofuSmtpPostStep(withOnceShape(o));
const constants={"deploy-user":"deploy","airflow-conf-dir":"/etc/airflow","airflow-logs-dir":"/var/lib/airflow/logs","airflow-uid":"50000","walg-conf-dir":"/etc/wal-g.d","rrsync-path":"/usr/local/bin/rrsync","docker-bridge-gateway":"172.17.0.1"};
export const parLookup=(k:string)=>`{{ lookup('env','COLORS_PAR_${k.toUpperCase().replaceAll("-","_")}') }}`;
export function dataFn(o:Opts):Opts{const no=o["provider-smtp"]==="no-infra",relay=no?{"smtp-server":o["no-infra-smtp-server"],"smtp-port":o["no-infra-smtp-port"],"smtp-username":o["no-infra-smtp-username"]}:{"smtp-server":"smtp.resend.com","smtp-port":587,"smtp-username":"resend"};const pk=no?"no-infra-smtp-password":"resend-password",v=String(o["postgres-version"]);return{...o,...relay,...constants,ip:String(o.ip||"192.168.0.1"),user:String(o.user||"root"),"host-alias":hostAlias(o),"walg-env-file":"/etc/wal-g.d/env","walg-prefix":`s3://${o["walg-r2-bucket"]}/${o.profile||"airflow"}`,pgdata:`/var/lib/postgresql/${v}/main`,"postgres-conf-dir":`/etc/postgresql/${v}/main`,"smtp-password-par":parName(pk),"smtp-password-lookup":parLookup(pk)}}
export function authorizedKeyLine(o:Opts,pub:string){return `restrict,command="/usr/local/bin/rrsync -wo ${o["dags-dest"]}" ${pub}`} export function deployKeysContent(o:Opts){const ls=github.publicKeys(o).map(k=>authorizedKeyLine(o,k.public));return ls.length?ls.join("\n")+"\n":""}
function pretty(v:any,i=0):string{if(Array.isArray(v))return v.length?`[ ${v.map(x=>pretty(x,i)).join(", ")} ]`:"[ ]";if(v&&typeof v==="object"){const es=Object.entries(v);if(!es.length)return"{ }";return`{\n${es.map(([k,x])=>`${" ".repeat(i+2)}${JSON.stringify(k)} : ${pretty(x,i+2)}`).join(",\n")}\n${" ".repeat(i)}}`;}return JSON.stringify(v??null)}
export const inventory=(d:any)=>pretty({all:{hosts:{[d["host-alias"]||"airflow"]:{ansible_host:d.ip,ansible_user:d.user}}}});
const seed=[{path:".github/workflows/deploy-dags.yml",t:tmpl("github/deploy-dags.yml",deployDags)},{path:"dags/hello_world.py",t:tmpl("github/hello_world.py",helloWorld)}];
export async function seedStep(o:Opts){const dir=toolDir(o,githubTool),r=scaffold(o,seed.map(x=>spec(x.t,`${dir}/seed/${x.path}`,dataFn(o))));if((r["red/exit"]??0)>0||o["red/event"]==="delete")return r;return{...r,"airflow/seed-files":seed.map(x=>({path:x.path,content:readFileSync(`${dir}/seed/${x.path}`,"utf8")}))}}
export async function ansibleLocalStep(o:Opts){const dir=toolDir(o,ansibleLocalTool),d=dataFn(o),ss=[spec(tmpl("ansible-local/ansible.cfg",localCfg),`${dir}/ansible.cfg`,d),spec(tmpl("ansible-local/inventory.ini",localInv),`${dir}/inventory.ini`,d),spec(tmpl("ansible-local/main.yml",localMain),`${dir}/main.yml`,d)];return ansibleWithSpec(o,{dir,inventory:"inventory.ini",playbooks:{create:"main.yml",delete:"main.yml"},extraVars:{host_alias:d["host-alias"],ip:d.ip,user:d.user,block_state:o["red/event"]==="delete"?"absent":"present"}},ss)}
const files:any={"authorized-keys":authorizedKeys,"docker-compose.yml":compose,"Caddyfile":caddy,"wal-g-wrapper":walgWrapper,"walg-basebackup":walgBase,"walg-check":walgCheck,"walg-notify":walgNotify};
export function ansibleRemoteSpecs(o:Opts,dir:string){const d=dataFn(o);return[spec(tmpl("ansible-remote/ansible.cfg",remoteCfg),`${dir}/ansible.cfg`,d),spec(tmpl("ansible-remote/main.yml",remoteMain),`${dir}/main.yml`,d),rawSpec(`${dir}/inventory.json`,inventory(d)),rawSpec(`${dir}/deploy_keys`,deployKeysContent(o)),...Object.entries(files).map(([n,c])=>spec(tmpl(`ansible-remote/files/${n}`,String(c)),`${dir}/files/${n}`,d))]}
export async function ansibleRemoteStep(o:Opts){const dir=toolDir(o,ansibleRemoteTool),r=scaffold(o,ansibleRemoteSpecs(o,dir));return ["build","delete"].includes(String(o["red/event"]))?r:ansibleStep(r,{dir,inventory:"inventory.json",playbooks:{create:"main.yml"},hostKeyChecking:false})}
