import{dirname}from"node:path";import{readPars,parName}from"red/cli";import{preflight}from"red/lifecycle";import*as dryRun from"red/dry-run";import*as progress from"red/progress";import*as tofu from"red/tofu";import{adviceAdd,workflow,type Opts}from"red/workflow";import*as github from"./github.ts";import*as tools from"./tools.ts";import{envErrors,secretErrors,stateErrors}from"./validate.ts";
const defaults={"compute-prevent-destroy":true,"provider-compute":"digitalocean","provider-dns":"cloudflare","provider-smtp":"resend","provider-backend":"local",workdir:".colors"};
async function stateOutput(o:Opts,dir:string){try{return(await tofu.outputs(dir,tools.backendCredentialEnv(o))).params as any}catch{return undefined}}
export async function adoptExistingState(o:Opts){const c=await stateOutput(o,tools.toolDir(o,tools.computeTool)),s=await stateOutput(o,tools.delegatedToolDir(o,tools.smtpTool));return{...o,...c,...s,...(c?{"once/compute-params":c}:{}),...(s?{"once/smtp-params":s}:{})}}
async function withKeys(o:Opts,real:boolean){if(real&&o["red/event"]==="create"){const[k,e]=await github.generateKeys(o);if(e)return{...o,"red/exit":1,"red/err":e};return{...o,"red/exit":0,"airflow/deploy-keys":k,...(k.length?{"airflow/key-dir":dirname(k[0].privateFile)}:{})}}return{...o,"red/exit":0,"airflow/deploy-keys":github.placeholderKeys(o)}}
export async function startStep(original:Opts,env:Record<string,string|undefined>=process.env){return preflight(original,{defaults,overlay:readPars,validators:[(_o,e)=>envErrors(e),(o)=>stateErrors(o),(o,_e,c)=>c.real&&["create","delete"].includes(String(c.event))?secretErrors(o):[],(o,_e,c)=>c.real&&c.event==="delete"&&o["compute-prevent-destroy"]?[`compute destruction is protected; set ${parName("compute-prevent-destroy")}=false to delete`]:[]],afterValidate:async(o,_e,c)=>c.real&&c.event==="delete"?{...await adoptExistingState(o),"red/exit":0}:withKeys(o,c.real)},env)}
export async function githubStep(o:Opts){const r=await tools.seedStep(o);return(r["red/exit"]??0)>0?r:github.githubStep(r)} export async function ansibleCleanupStep(o:Opts){return tools.ansibleRemoteStep(await tools.ansibleLocalStep(o))}
export function wireFn(s:string,o:Opts){if(o["red/event"]==="delete")return({"airflow/start":[startStep,"airflow/github"],"airflow/github":[githubStep,"airflow/ansible-cleanup"],"airflow/ansible-cleanup":[ansibleCleanupStep,"airflow/smtp-post"],"airflow/smtp-post":[tools.smtpPostStep,"airflow/dns"],"airflow/dns":[tools.dnsStep,"airflow/smtp","airflow/compute"],"airflow/smtp":[tools.smtpStep],"airflow/compute":[tools.computeStep]}as any)[s];return({"airflow/start":[startStep,"airflow/compute"],"airflow/compute":[tools.computeStep,"airflow/smtp"],"airflow/smtp":[tools.smtpStep,"airflow/dns"],"airflow/dns":[tools.dnsStep,"airflow/smtp-post"],"airflow/smtp-post":[tools.smtpPostStep,"airflow/ansible-local","airflow/ansible-remote"],"airflow/ansible-local":[tools.ansibleLocalStep],"airflow/ansible-remote":[tools.ansibleRemoteStep,"airflow/github"],"airflow/github":[githubStep]}as any)[s]}
export function backendAdvice(dir:(o:Opts)=>string,tool:string){return tofu.conventionalBackendAdvice({dir,key:o=>`${o.profile||"airflow"}/${tool}.tfstate`})}
export const sideEffectingSteps=["airflow/compute","airflow/smtp","airflow/dns","airflow/smtp-post","airflow/ansible-local","airflow/ansible-remote","airflow/ansible-cleanup","airflow/github"];
function create(){let w=workflow({start:"airflow/start",wireFn});for(const[t,own]of[[tools.computeTool,true],[tools.smtpTool,false],[tools.dnsTool,false],[tools.smtpPostTool,false]]as const){const d=own?(o:Opts)=>tools.toolDir(o,t):(o:Opts)=>tools.delegatedToolDir(o,t);w=adviceAdd(w,`airflow/${t===tools.computeTool?"compute":t.replace("tofu-","")}`,"before","airflow.workflow/backend",backendAdvice(d,t))}return dryRun.advise(progress.advise(w),sideEffectingSteps)}export const airflowWorkflow=create();
