(ns io.github.getcolors.airflow.github
  "The DAG repository, its deploy key, and the Actions environment they meet in.

  This is a fifth concern rather than a step in `tools`: nothing here renders a
  template or drives OpenTofu or Ansible, and the credentials it moves belong to
  a service outside the four provider slots entirely.

  ONCE's `github.clj` is the ancestor and most of it transplants unchanged — a
  keypair per create, nothing stored, the private half published to an Actions
  environment named after the profile alongside the host, the login and the
  server's host key. Three things differ, and each is deliberate:

  * **One repository, not a group per application.** ONCE groups applications by
    `:github` because one image can answer for several hosts. This package has
    exactly one repository, `dags-repo`, so the grouping collapses to a single
    entry and the hosts a key is allowed to act on stop being part of its
    authority (see `authorized-key-line`).

  * **The repository is created, and seeded once.** ONCE assumes the repository
    already exists. Here it is part of desired state, so a create makes it —
    private — and puts a workflow and a hello-world DAG in it the first time.
    After that its contents are never written again: Colors converges on every
    create and DAGs are the user's work, so a converging seed would overwrite
    real DAGs with the example. Walter's clone-once rule is the precedent.

  * **Delete never deletes the repository.** Destroying compute is recoverable
    through WAL-G; destroying the repository is not, and it is the one artifact
    here that cannot be rebuilt from desired state. Delete withdraws the
    credentials and leaves the repository standing.

  Keys are generated by `ssh-keygen` rather than in process, and the private
  half is never passed as an argument: `green.process` closes a child's stdin,
  so it cannot be piped either, and instead the key stays in the 0600 file
  `ssh-keygen` wrote while `gh` reads it through a shell redirect. That keeps it
  out of the process table the same way stdin would have."
  (:require
   [clojure.java.io :as io]
   [clojure.string :as str]
   [green.process :as process]))

(def ^:private run-timeout-ms 30000)

(def deploy-user
  "The unprivileged account CI logs in as.

  It needs no sudo at all, which is the sharpest difference from ONCE — that
  key carries `sudo once update`, this one carries a directory. Duplicated here
  rather than read from `tools` because `tools` requires this namespace, and
  the value is the same three characters in the authorized_keys line and in the
  published variable."
  "deploy")

(def ^:private placeholder-public
  "The public key a build renders.

  Generation is a create-time side effect, so build and dry-run need a value
  that never changes. In ONCE this exists so three colours render byte-identical
  artifacts; here parity is moot and the reason has shifted rather than gone
  away — `scripts/golden.sh` diffs rendered output, and a fresh key per build
  would break every golden on every run."
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBUILDPLACEHOLDER0000000000000000000000")

(defn dags-repo
  "The one repository this package manages, or nil when desired state names
  none. Validation requires it, so nil only occurs in a test or a REPL."
  [opts]
  (not-empty (str/trim (str (:dags-repo opts)))))

(defn key-comment
  "Identifies the key on the box, and the value the authorized-keys reconciler
  groups generations by.

  Carries no timestamp: the comment is rendered into an artifact `golden.sh`
  diffs, and a clock reading there would break every run. Ordering for retention
  comes from position in authorized_keys instead.

  The `/` is slugged because this sits in an authorized_keys comment field.
  Nothing parses it back apart — retention compares whole comments — so a
  profile, owner or repository containing a dash stays unambiguous."
  [opts]
  (format "airflow-deploy-%s-%s"
          (or (:profile opts) "default")
          (str/replace (str (dags-repo opts)) "/" "-")))

(defn placeholder-keys
  "What a build or a dry-run uses in place of generated keys."
  [opts]
  (if-let [repo (dags-repo opts)]
    [{:github repo
      :public (str placeholder-public " " (key-comment opts))}]
    []))

(defn- keygen-args
  [opts path]
  ["ssh-keygen" "-t" "ed25519" "-N" "" "-q"
   "-C" (key-comment opts)
   "-f" path])

(defn generate-keys
  "Generate the deploy keypair into a private directory.

  Returns `[keys error]`; `keys` carries the public key inline and the private
  key only as a path, so the secret never enters the opts map. The caller
  removes `:airflow/key-dir` once publication is done.

  A vector of one rather than a bare map, so the shape matches ONCE's and the
  reconciler on the box — which merges a list — needs no special case for the
  single-repository package."
  ([opts] (generate-keys opts process/run-with-timeout))
  ([opts run-fn]
   (if-let [repo (dags-repo opts)]
     (let [dir (str (java.nio.file.Files/createTempDirectory
                     "airflow-deploy"
                     (into-array java.nio.file.attribute.FileAttribute [])))
           path (str (io/file dir "key-0"))
           result (run-fn (keygen-args opts path) {} run-timeout-ms)]
       (if-not (zero? (:exit result -1))
         [nil (format "ssh-keygen failed for %s: %s"
                      repo (str/trim (str (:err result))))]
         [[{:github repo
            :public (str/trim (slurp (str path ".pub")))
            :private-file path}]
          nil]))
     [[] nil])))

(defn public-keys
  "The render-facing view: public key only. `tools` builds the authorized_keys
  line from this, so no private key can reach a template."
  [opts]
  (mapv #(select-keys % [:public])
        (or (:airflow/deploy-keys opts) [])))

;;; --------------------------------------------------------------- gh commands

(defn- env-name
  [opts]
  (or (:profile opts) "default"))

(defn- shell-quote
  [s]
  (str "'" (str/replace (str s) "'" "'\\''") "'"))

(defn host-key-args
  "Read the server's own SSH host key over the administrative connection, so the
  workflow can pin it instead of running ssh-keyscan on every deploy.

  This is still trust on first use — nothing here has a prior binding for that
  key either. What it changes is the window: CI stops asking the network who the
  server is on every deploy and starts comparing against a value captured once,
  so a substituted key is detected from then on."
  [opts]
  ["ssh" "-o" "BatchMode=yes" "-o" "ConnectTimeout=10"
   "-o" "StrictHostKeyChecking=accept-new"
   (str (or (:user opts) "root") "@" (:ip opts))
   "cat /etc/ssh/ssh_host_ed25519_key.pub"])

(defn known-hosts-line
  "A known_hosts entry for `ip` from an `ssh_host_*.pub` file's contents. The
  trailing comment is dropped: it is the server's own hostname at key generation
  time and means nothing to a client."
  [ip pub]
  (let [[algo body] (str/split (str/trim (str pub)) #"\s+")]
    (when (and algo body (str/starts-with? algo "ssh-"))
      (format "%s %s %s" ip algo body))))

(defn fetch-host-key
  "The known_hosts line for this server, or nil when it cannot be read.

  A failure here is not fatal: the credentials are still worth publishing, and a
  workflow that finds no SSH_KNOWN_HOSTS can say so itself."
  [opts run-fn]
  (let [result (run-fn (host-key-args opts) {} run-timeout-ms)]
    (when (zero? (:exit result -1))
      (known-hosts-line (:ip opts) (:out result)))))

(defn create-repo-commands
  "Bring the repository into being, private.

  Private is not a default worth inheriting: DAGs carry business logic, and a
  public one is a mistake you only make once. `--private` is passed explicitly
  so the account's own default repository visibility cannot make this public."
  [opts]
  [{:label (format "create %s" (dags-repo opts))
    :args ["gh" "repo" "create" (dags-repo opts) "--private"
           "--description" (format "Airflow DAGs for %s, deployed by colors"
                                   (:airflow-host opts))]}])

(defn publish-commands
  "The gh invocations that publish the deploy credentials. Pure, so a test can
  assert the exact argv sequence without a process.

  The address, the login and the destination are variables rather than secrets:
  DNS already reveals the host, and masking them only makes CI logs harder to
  read. The private key is the one secret.

  The environment is created first, with an idempotent PUT. A workflow that
  names an environment does bring it into being — which would have kept this
  token off admin scope — but that only helps once the workflow has been wired
  to the environment, and nothing here can guarantee that came first. Writing
  into an environment that does not exist is a 404."
  [opts {:keys [github private-file]}]
  (let [env (env-name opts)
        base ["--repo" github "--env" env]]
    [{:label (format "%s environment %s" github env)
      :args ["gh" "api" "--method" "PUT" "--silent"
             (format "repos/%s/environments/%s" github env)]}
     {:label (format "%s SERVER_IP" github)
      :args (concat ["gh" "variable" "set" "SERVER_IP"] base
                    ["--body" (str (:ip opts))])}
     {:label (format "%s SERVER_USER" github)
      :args (concat ["gh" "variable" "set" "SERVER_USER"] base
                    ["--body" deploy-user])}
     {:label (format "%s SSH_KNOWN_HOSTS" github)
      :args (concat ["gh" "variable" "set" "SSH_KNOWN_HOSTS"] base
                    ["--body" (str (:airflow/known-hosts opts))])}
     ;; Redirected rather than passed: `green.process` closes a child's stdin, so
     ;; the key cannot be piped, and an argument would put it in the process
     ;; table. The 0600 file ssh-keygen wrote is the only place it exists.
     {:label (format "%s SSH_PRIVATE_KEY" github)
      :args ["sh" "-c"
             (str "gh secret set SSH_PRIVATE_KEY --repo " (shell-quote github)
                  " --env " (shell-quote env)
                  " < " (shell-quote private-file))]}]))

(defn- b64
  [s]
  (.encodeToString (java.util.Base64/getEncoder)
                   (.getBytes (str s) "UTF-8")))

(def ^:private seed-retries
  "How many times a seed write is retried, and how long between attempts.

  A repository is not immediately usable through the contents API after
  `gh repo create` — a PUT issued straight afterwards returns 404 while GitHub
  finishes initialising it. That is not theoretical: it is what left the first
  real deployment with a created, private, and completely empty DAG repository,
  and the error was invisible because the parallel `ansible-remote` branch
  failed in the same run and its message won.

  Retried rather than preceded by a fixed sleep, because the delay is GitHub's
  and not knowable — and a sleep long enough to be safe is one nobody wants on
  every create."
  {:times 6 :delay-ms 2500})

(defn seed-file-missing?
  "Whether `path` is absent from the repository.

  A 404 also covers the repository not being ready yet, which is exactly the
  window the retry above exists for — so a brand-new repository reports every
  seed file as missing, which is correct."
  [opts run-fn path]
  (not (zero? (:exit (run-fn ["gh" "api" "--silent"
                              (format "repos/%s/contents/%s" (dags-repo opts) path)]
                             {:extra-env {"GH_TOKEN" (str (:github-token opts))}}
                             run-timeout-ms)
                     -1))))

(defn seed-commands
  "Write the starter workflow and the hello-world DAG, one command per file.

  Through the contents API rather than a clone and a push: there is no working
  tree to make, no git identity to configure, and an empty repository gets its
  default branch from the first file written to it. `dags-branch` is named
  explicitly so the branch the workflow syncs from is the branch that appears,
  rather than whatever the account's default happens to be.

  **Seeding is per missing file, not per newly created repository — a
  deliberate departure from the original design.** That rule was one-shot: it
  fired only for a repository the same run had just made, and it raced with
  GitHub's own initialisation. When the race was lost the repository stayed
  empty forever, because every later create saw it already existed and skipped
  seeding. Silently, and on the one path a new user hits first.

  Keyed on the file instead, the seed is self-healing: whatever the race did,
  the next create finishes the job. The property that actually matters is
  preserved and is in fact stronger — a path that exists is never written, so
  the operator's own `hello_world.py` is safe even though the repository is not
  new.

  What it gives up, stated because it is real: deleting a seeded file means the
  next create puts it back. That is a nuisance, where the alternative was a
  deployment with no deploy workflow at all."
  [opts files]
  (let [repo (dags-repo opts)
        branch (or (not-empty (str (:dags-branch opts))) "main")]
    (mapv (fn [{:keys [path content]}]
            {:label (format "%s seed %s" repo path)
             :retry seed-retries
             :args ["gh" "api" "--method" "PUT" "--silent"
                    (format "repos/%s/contents/%s" repo path)
                    "-f" (str "message=Seed " path " (colors airflow)")
                    "-f" (str "branch=" branch)
                    "-f" (str "content=" (b64 content))]})
          files)))

(defn revoke-commands
  "The gh invocations that withdraw the deploy credentials.

  Needs no key material, so it works with the box already destroyed — which is
  why it runs before teardown rather than after. It does not touch the
  repository itself."
  [opts]
  (let [repo (dags-repo opts)
        env (env-name opts)
        base ["--repo" repo "--env" env]]
    [{:label (format "%s SERVER_IP" repo)
      :args (concat ["gh" "variable" "delete" "SERVER_IP"] base)}
     {:label (format "%s SERVER_USER" repo)
      :args (concat ["gh" "variable" "delete" "SERVER_USER"] base)}
     {:label (format "%s SSH_KNOWN_HOSTS" repo)
      :args (concat ["gh" "variable" "delete" "SSH_KNOWN_HOSTS"] base)}
     {:label (format "%s SSH_PRIVATE_KEY" repo)
      :args (concat ["gh" "secret" "delete" "SSH_PRIVATE_KEY"] base)}]))

(defn create-commands
  "Every gh invocation a create makes, in order.

  The ordering is load-bearing on a first run, and it is the reverse of what
  reads naturally: repository, then credentials, then seed. Pushing the seed
  first triggers the workflow before the key it needs exists, which looks like a
  broken install on a fresh setup rather than the race it is.

  `seed-files` is already narrowed to the ones missing from the repository, so
  this stays a pure function of what it is handed."
  [opts {:keys [exists? seed-files]}]
  (vec (concat (when-not exists? (create-repo-commands opts))
               (mapcat #(publish-commands opts %) (:airflow/deploy-keys opts))
               (seed-commands opts seed-files))))

;;; ------------------------------------------------------------------ the step

(defn- token-env
  [opts]
  {"GH_TOKEN" (str (:github-token opts))})

(defn repo-exists?
  "Whether the repository is already there.

  A probe rather than an assumption in either direction: creating one that
  exists fails, and seeding one that exists overwrites the operator's DAGs. Only
  the exit code is read — `gh repo view` prints the repository, and nothing here
  needs any of it."
  [opts run-fn]
  (zero? (:exit (run-fn ["gh" "repo" "view" (dags-repo opts) "--json" "name"]
                        {:extra-env (token-env opts)}
                        run-timeout-ms)
                -1)))

(defn- cleanup!
  [opts]
  (when-let [dir (:airflow/key-dir opts)]
    (doseq [f (reverse (file-seq (io/file dir)))]
      (.delete ^java.io.File f)))
  (-> opts
      (dissoc :airflow/key-dir)
      (update :airflow/deploy-keys #(mapv (fn [k] (dissoc k :private-file)) (or % [])))))

(defn github-step
  "Publish on create, revoke on delete, do nothing otherwise.

  `wire-fn` runs the same branch for `:build` and `:create`, so the event check
  here is what keeps a build from reaching GitHub; `side-effecting-steps` only
  covers `--dry-run`.

  A revoke that fails because there is nothing to revoke is not an error: delete
  has to be re-runnable, and a missing secret is the state it is trying to
  reach."
  ([opts] (github-step opts process/run-with-timeout))
  ([opts run-fn]
   (let [event (:green/event opts)
         delete? (= :delete event)]
     (cond
       (not (contains? #{:create :delete} event)) opts
       (nil? (dags-repo opts)) (assoc opts :green/exit 0)

       :else
       (let [opts (cond-> opts
                    (not delete?) (assoc :airflow/known-hosts
                                         (fetch-host-key opts run-fn)))
             commands (if delete?
                        (revoke-commands opts)
                        (let [exists? (repo-exists? opts run-fn)]
                          (create-commands
                           opts
                           {:exists? exists?
                            ;; Probed rather than assumed from `exists?`. A
                            ;; repository that exists may still be missing the
                            ;; seed — which is precisely the state a lost race
                            ;; leaves behind, and the state this deployment was
                            ;; actually in.
                            :seed-files
                            (filterv #(seed-file-missing? opts run-fn (:path %))
                                     (:airflow/seed-files opts))})))
             failure (reduce
                      (fn [_ {:keys [args label retry]}]
                        (let [{:keys [times delay-ms] :or {times 1 delay-ms 0}} retry
                              result (loop [attempt 1]
                                       (let [r (run-fn (vec args)
                                                       {:extra-env (token-env opts)}
                                                       run-timeout-ms)]
                                         (if (or (zero? (:exit r -1)) (>= attempt times))
                                           r
                                           (do (Thread/sleep delay-ms)
                                               (recur (inc attempt))))))]
                          (if (or delete? (zero? (:exit result -1)))
                            nil
                            (reduced (format "gh failed for %s: %s"
                                             label
                                             (str/trim (str (:err result))))))))
                      nil
                      commands)
             opts (cleanup! opts)]
         (if failure
           (assoc opts :green/exit 1 :green/err failure)
           (assoc opts :green/exit 0)))))))
